argoproj/argoproj

community/README.md

Added direct community meeting links, Slack organization link, and updated member project links.

[doc] Update README.md

---

README.md

Resolves https://github.com/argoproj/argoproj/issues/7

docs: add community calendar to README

---

community/decision-making.md

Documents the decision making process to be used by Argo Project committees.

docs: Argo decision making process

---

.github/ISSUE_TEMPLATE/project-onboarding.md
community/ecosystem-projects.md

Documents describe what is Argoproj ecosystem project and propose the onboarding process for such projects.
Closes https://github.com/argoproj/argoproj/issues/14

docs: Ecosystem project onboarding

---

README.md
community/dco-signoff-hook/prepare-commit-msg

docs: add dco-signoff-hook

---

README.md
community/README.md

docs:update community/README to use DCO

---

OWNERS

Code contributions:
- Argo CD https://github.com/argoproj/argo-cd/pulls?q=is%3Apr+author%3Asbose78+
- Argo Workflows https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3Asbose78+is%3Aclosed
Governance discussions
- https://github.com/argoproj/argoproj/issues?q=is%3Aissue+author%3Asbose78+
- https://github.com/argoproj/argoproj/pulls/sbose78

docs: Add Shoubhik Bose as reviewer

---

OWNERS

Signed-off-by: Dan Garfield <dan@todaywasawesome.com>

docs: Add Dan Garfield to reviewers.

---

MAINTAINERS.md

Aggregation of maintainers from all sub projects with affiliation and if the maintainer has a vote, per Argo governance.

docs: Create project-wide maintainer file

---

community/GOVERNANCE.md

Updating Governance to formalize voting procedures and align with current processes.

docs: Updating GOVERNANCE.md

---

community/ecosystem-projects/README.md

Will be needed if folks are Okay with https://github.com/argoproj/argoproj/pull/32

docs: Add directory for ecosystem projects

---

community/README.md

docs: Update community README

---

community/GOVERNANCE.md

docs: add link to community calendar

---

MAINTAINERS.md

Updating MAINTAINERS.md from 8/19 meeting

docs:Updating MAINTAINERS.md

---

MAINTAINERS.md

Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>

docs: Update my affiliation

---

MAINTAINERS.md

Signed-off-by: hari rongali <hari_rongali@intuit.com>

docs: update remington afflilation

---

hack/tallyvotes.py

Wrote a script that uses the github cli to tally votes based on MAINTAINERS.md. Output looks like:
```
MAINTAINER          VOTE
----------          ----
ash2k               0
todaywasawesome     1
chetan-rns          1
edlee2121           1
jannfis             1
wtam2018            1
khhirani            1
jgwest              1
sbose78             0
dthomson25          0
simster7            1
terrytangyuan       1
hblixt              1
xianlubird          0
dtaniwaki           1
alexmt              1
jessesuen           1
VaibhavPage         1
ishitasequeira      1
sarabala1979        0
rbreeze             1
wanghong230         0
alexec              0
tetchel             0
mayzhang2000        1
whynowy             0
reginapizza         1
COMMUNITY-USER      VOTE
--------------      ---- …
```

feat: script to tally votes

---

MAINTAINERS.md

Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

docs: add Andrii Perenesenko to MAINTAINERS.md and remove inactive members

---

MAINTAINERS.md

@jessesuen isn't the same person as @alexmt 
Signed-off-by: Dan Garfield <dan@codefresh.io>

Fix Alex M's link

---

community/membership.md

docs: Clarified convention for role changes

---

MAINTAINERS.md

Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

docs: add new argoproj maintainers

---

MAINTAINERS.md
OWNERS

I'm honored to be added to the approvers list. Thanks.
Signed-off-by: Keith Chong <kykchong@redhat.com>

docs: Update approvers list

---

MAINTAINERS.md

Excited to be part of the ArgoCD team! Thanks @alexmt @jessesuen @jannfis for sponsoring!
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>

chore: Add myself to ArgoCD reviewers

---

MAINTAINERS.md
OWNERS

Signed-off-by: Leonardo Luz Almeida <leonardo_almeida@intuit.com>

chore: add Leo and Michael in the approvers list

---

MAINTAINERS.md

- Removed michael and leo dupes
- restored alphabetical order

chore:Updating MAINTAINERS.md

---

MAINTAINERS.md

docs: Add tczhao as workflow reviewer

---

community/SIG-GOVERNANCE.md

docs: Added SIG-GOVERNANCE.md

---

MAINTAINERS.md

- Switching company for Kareena Hirani
- alphabetical order by last name.

chore: Updating maintainers.md

---

proposals/argocd-metric-extension.md

Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>
Architecture:
Phase1:
Phase2:
screen shot:

[PROJECT ONBOARDING] ArgoCD Metrics Extension

---

proposals/argo-metaverse.md

Argo Metaverse proposal

---

community/feature-status.md

This PR introduces the documentation for the new Feature Status process. 
Signed-off-by: Leonardo Luz Almeida <leonardo_almeida@intuit.com>

Add Feature Status documentation

---

community/GOVERNANCE.md
community/membership.md

Added quorum requirement for governance votes.
Clarified the role of Lead.

docs: GOVERNANCE: Added quorum requirement for governance votes and clarified the role of subproject lead

---

MAINTAINERS.md

This will look much better.
Before:
After:
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>

chore: Add newline to people with multiple roles

---

MAINTAINERS.md

He was my ex-colleague at Alibaba and "Chen" should be his last name.
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>

Correct xianlubird's last name

---

MAINTAINERS.md

Every quarter, the Argoproj maintainers review requests for project membership and promotions (read about the roles [here](https://github.com/argoproj/argoproj/blob/master/community/membership.md#community-membership)). The changes below recognize the incredible efforts ([graphed on CNCF devstats](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=All&var-users=%22juliev0%22&var-users=%22zachaller%22&var-users=%22terrytangyuan%22&var-users=%22wilsonwu%22&var-users=%22Joibel%22&var-users=%22dfarr%22&var-users=%22isubasinghe%22&var-users=%22blakepettersson%22&var-users=%22gdsoumya%22&from=now-6M&to=now)) and commitment to the project by these people. Thank you so much!
Congrats to the following …

Argoproj promotions/membership

---

README.md

These are no longer news and are part of the contributing guide https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md

docs: Remove NEWS section since they are no longer NEWS

---

OWNERS

Added updates from https://github.com/argoproj/argoproj/pull/280 and https://github.com/argoproj/argoproj/pull/257

Update OWNERS based on recent membership updates

---

community/membership.md

Document what we've been doing in practice.

Clarify scoped reviewer/approver roles in membership.md

---

.github/ISSUE_TEMPLATE/membership.md

See discussions in https://cloud-native.slack.com/archives/C020XM04CUW/p1707928769306159

Add notes on publicizing membership in membership request

---

MAINTAINERS.md

Change from Procore to GitHub
I switched jobs in 3/2024
Also, I go by JM, changed name to match.

chore: change company for jmeridth (JM)

---

sigs/sig-marketing/README.md

Jenny has been helping sig-marketing for the last few months primarily by helping create social media posts and adding her voice to meetings.

Add Jenny to sig-marketing, fix typos, make alphabetical.

---

sigs/sig-marketing/README.md

Meghan left Intuit, so updating affiliation to none for now.

Updating Meghan afiliation

---

sigs/sig-marketing/README.md

Signed-off-by: Samuel Tauil <samueltauil@gmail.com>

Add How to Join, Interested Party and Emeritus sections

---

community/promotion-checklists/member-promotion-checklist.md
community/promotion-checklists/promotion-process.md
community/promotion-checklists/reviewer-promotion-checklist.md

docs: promotion membership checklist

---

sigs/sig-marketing/README.md

Add Austin Blankenship to SIG Marketing

chore: add austin to sig marketing

---

proposals/argocd-mcp-server.md

Argo CD MCP Server is an implementation of [Model Context Protocol (MCP)](https://modelcontextprotocol.io/) server for [Argo CD](https://argo-cd.readthedocs.io/en/stable/), enabling AI assistants to interact with your Argo CD applications through natural language. This server allows for seamless integration with Visual Studio Code and other MCP clients through stdio and HTTP stream transport protocols.
More details and documentation is available at https://github.com/akuity/argocd-mcp

docs: argocd-mcp onboarding to argoproj-labs
