- community/decision-log.md
Now that the Argo Project is a part of the CNCF, we should revise the Argo CLA to follow CNCF guidelines.
> decision: Revise Argo CLA to follow CNCF guidelines

- .github/ISSUE_TEMPLATE/membership.md
- community/GOVERNANCE.md
- community/README.md
- community/membership.md
Document Argo Project community membership roles, requirements, & responsibilities. This was adapted from the Kubernetes community membership doc, as well as the open telemetry community membership doc (which was copied from kubernetes).
> docs: Community Membership roles, requirements, & responsibilities

- README.md
> docs: Update news with move from CLA to DCO

- community/membership.md
As discussed in today's contributor's meeting today, it was proposed to allow Argoproj members to moderate GitHub discussions (e.g. mark answers as accepted) to help share the load of answering questions from the community.
Signed-off-by: Jesse Suen <jessesuen@gmail.com>
> feat: members should have ability to moderate github discussions

- community/decision-log.md
Argo approvers may assign the role of reviewer to  non-coding contributors who actively contribute and play a significant role in the community.
> docs: Allow non-coding reviewers

- SECURITY.md
This updates the proxy security policy to a more sensible version, and also updates the e-mail contacts.
Link to 
Signed-off-by: jannfis <jann@mistrust.net>
> docs: Update security policy

- community/membership.md
Discussed and agreed in both the Argoproj contributors meeting as well as maintainers meeting on 8/12 and 8/13 respectively, we would like to expand the privileges of all Argoproj members such that they can triage (label) issues and moderate GitHub discussions. This involves the following changes:
1. Creation of a "members" GitHub team. All members of the Argoproj and Argoproj-labs organization will also be members of the "members" GitHub team.
2. For all public git repositories in argoproj and argoproj-labs, the "members" GitHub team will be added to the repository with the "Triage" role. This needs to be done per repository, as there is no automatic way to do this in GitHub.
For additional details on what the Triage role is able to do, see [GitHub …
> feat: expand permissions of members to include Triage capability

- community/membership.md
MEMBERS.md still had a reference to 'TC', which is no longer valid. Updated to "maintainers group". 
As this is just a fix to get the document aligned with our governance, no vote should be needed. 
Signed-off-by: Henrik Blixt <henrikblixt@gmail.com>
> docs: Updating MEMBERS.md

- community/ecosystem-projects.md
Followup action from Sep 7 maintainers meeting. Documenting the use of `quay.io/argoprojlabs` for labs projects.
Signed-off-by: Jesse Suen <jessesuen@gmail.com>
> docs: document use of quay.io/argoprojlabs intended to be used for labs projects

- SECURITY.md
- community/ecosystem-projects.md
This change adds a security disclaimer about argoproj-labs projects and also requires all labs project have a SECURITY.md which lists contacts for reporting vulnerabilities.
Signed-off-by: Jesse Suen <jesse@akuity.io>
> docs: add security disclaimer and requirement for argoproj-labs projects

- README.md
CLOMonitor is a bit opinionated about how information should be presented. This PR should significantly improve the CLOMonitor score and surface more information to the top-level README. https://clomonitor.io/projects/cncf/argo#argoproj
> docs: align with CLOMonitor expectations

- community/ecosystem-projects.md
The ApplicationSet controller is no longer an experiment feature ecosystem project, but we can re-phrase so that it serves as a useful example of how the process can work.
> ecosystem-projects: update ApplicationSet status

- MAINTAINERS.md
Every quarter, the Argoproj maintainers review requests for project membership and promotions (read about the roles [here](https://github.com/argoproj/argoproj/blob/master/community/membership.md#community-membership)). The changes below recognize the incredible efforts ([graphed on CNCF devstats](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=All&var-users=%22morey-tech%22&var-users=%22alexef%22&var-users=%22jaideepr97%22&var-users=%22jmeridth%22&from=now-6M&to=now)) and commitment to the project by these four people. Thank you so much!
Congrats to Alex Eftimie (@alexef) on their promotion to Reviewer for Argo CD!
An additional congratulations to the following folks for becoming Argoproj members:
* …
> Argoproj promotions/membership

- community/membership.md
- Currently, Membership & Promotions occur on a quarterly basis, but this is not mentioned anywhere in the docs
- c.f. https://github.com/argoproj/argoproj/issues?q=%22Argoproj+promotions%2Fmembership%22 which say quarterly and have occurred Nov, Feb, May
- Add a tiny note about quarterly changes under the "Change in membership roles" section
> docs: specify that role changes occur quarterly

- .github/ISSUE_TEMPLATE/membership.md
- figured this looks a little nicer once the issue is created and in preview mode
- stumbled upon this while filing for my own membership in #221 😅
- Convert the parenthesized links in the membership template to Markdown links
See [GH Preview](https://github.com/argoproj/argoproj/blob/b87c02a1e550fc2b0590c79c4b71b2c656b6a870/.github/ISSUE_TEMPLATE/membership.md)
> docs: markdownify links in membership template

- community/membership.md
The Argoproj approvers and leads have selected several contributors to be "scoped" approvers, i.e. folks who are able to merge some (but not all) types of pull requests in their subproject.
To keep membership meetings focused and efficient, we'd like to clarify the governance documentation to specify that the meetings are attended by "full approvers," i.e. contributors who have been granted access to merge _any_ PR in their subproject.
We think this limitation will be helpful as we try out the new "scoped approvers" system.
Needed to pass:
* Votes by 30% of maintainers (at least 13): ✔️   currently 17 votes
> document who is expected to attend membership meetings

- MAINTAINERS.md
In the last Argoproj membership meeting, four contributors were selected for promotion to new "scoped" roles. These roles recognize the contributors' expertise in a particular area of an Argo subproject and, in the case of scoped approvers, grants access to merge PRs in their area of expertise.
This is the first time Argoproj has granted scoped reviewer/approver roles, and it's a testament to Argo's growing strength in number and diversity of active contributors. 
A hearty thanks and congratulations goes to these four!
* Dan Garfield (@todaywasawesome) to Approver(docs) in Argo CD
* Justin Marquis (@34fathombelow) to Approver(docs/ci) in Argo CD
* Nicholas Morey (@morey-tech) to Reviewer(docs) in Argo CD
* Blake Pettersson (@blakepettersson) to Approver(docs) in Argo CD
> Argoproj (scoped) promotions

- community/membership.md
- there are some "triage-level" permissions that I thought I would have but apparently don't, so wanted to document those more explicitly
- which should hopefully result in more clarity / less ambiguity / less confusion amongst the community, especially Member+
- Discussions and Issues vs. PR permissions differ fairly significantly
- can't hide or edit issue or PR comments, which I often do as part of triage etc
- but can do so in discussions
- but can't do so on the opening comment of a discussion (which may be missing syntax highlighting, have spelling or grammatical errors, etc)
- Have [learned](https://cloud-native.slack.com/archives/C0510EUH90V/p1692120705627719) that I can't add labels nor modify existing labels
- it is often useful to [create new …
> docs: be specific about the permissions of Members

- community/membership.md
I think we'd like for future Approvers to show us both their own PRs as well as show us their reviews, the latter because they will be able to merge PRs and need to be trusted to do so, and the former because it's probably necessary to spend time with code making modifications to it in order to be good at doing reviews for that code.
> docs: approver role should clarify that PR contributions and PR reviews are both expected for Approver role

- sigs/sig-marketing/README.md
Voted on and approved by Argo Maintainers in Dec 5th 2023 meeting.
> Set Dan Garfield as sig-marketing lead

- community/GOVERNANCE.md
- community/membership.md
Needed more clarity to distinguish different roles and structure of the membership doc. Context https://github.com/argoproj/argo-workflows/pull/12359#discussion_r1439718331
Preview of the updated TOC:
> Clearer headings and minor improvements to membership governance docs

- sigs/sig-marketing/README.md
Meghan served as ArgoCon co-chair in Chicago and is a regular contributor to sig-marketing.
> Add Meghan Murphy to sig-marketing

- sigs/sig-marketing/README.md
Caelan has been a huge booster and link in the Argo Workflows community and has helped review talks and organize two ArgoCon's. I think his help has been invaluable and I propose he be added to sig-marketing.
> Add Caelan Urquhart to sig-marketing

- sigs/sig-security/README.md
Michael has been defacto sig-lead for a while. He's organized better reporting systems, takes the lead on the administration of the project, and he has several times made proactive changes to improve project security and orientation. He is the natural choice for the job.
> Nominate Michael and Jann as sig-leads for sig-security

- MAINTAINERS.md
- OWNERS
It is with great pleasure I am putting forward @crenshaw-dev as Argo CD Lead. Michael has been invaluable to the Argo project and has effectively been leading Argo CD for the past few years, but just without the title.
In addition to Michael's [storied code contributions](https://github.com/argoproj/argo-cd/commits?author=crenshaw-dev) to Argo CD, he has been an effective and patient steward of the project, while also leading Argo security sig as well.
I think others will agree that this has been long overdue.
> Promote Michael Crenshaw as Argo CD Lead

- .github/ISSUE_TEMPLATE/membership.md
- .github/ISSUE_TEMPLATE/promotion-approver.md
- .github/ISSUE_TEMPLATE/promotion-reviewer.md
- `area/github-membership` [doesn't exist](https://github.com/argoproj/argoproj/labels) -- I'm not sure if it did at some point though
- I added [`type/membership-request`](https://github.com/argoproj/argoproj/labels/type%2Fmembership-request) and [`type/promotion-request`](https://github.com/argoproj/argoproj/labels/type%2Fpromotion-request) recently once I had Approver/write permissions, so let's use those
- I also labeled lots of previous requests with those
- [`type/*`](https://github.com/argoproj/argo-workflows/labels?q=type%2F) matches the categorization of issue ["types"](https://github.com/argoproj/argo-workflows/blob/ed55b02992d5774e6d7ccb56bef73c27cb0c5fd2/.github/ISSUE_TEMPLATE/bug_report.yaml?plain=1#L3) we have in Workflows
- whereas `area/*` is for the _scope_ of the …
> fix(gh): use correct labels in issue templates

- sigs/sig-security/README.md
I would like to propose adding Blake Pettersson to sig security to help respond to CVE reports. Blake is an active Argo CD maintainer. He implemented several features and multiple bug fixes and has already worked on CVE.
> docs: Add Blake Pettersson to sig-security

- sigs/sig-scalability/README.md
- At Elastic, we're increasingly interested in getting involved in helping the community with aspects of scaling Argo CD; thus, I'd very much like to be involved in this SIG
> chore(docs): add z3r0sum (stephen schmidt) to SIG Scalability

- sigs/sig-scalability/README.md
During sig-scalability [meeting on 2024/9/10](https://docs.google.com/document/d/1kukOugDjvZf_-dLRiLyW2fsAk7Nb44Ds0G7IuzrBBOM/edit) @daniel-codefresh brought that the SIG should have leads so they can take over lead and also admin tasks.
The action item was to create this PR were @csantanapr and @ishitasequeira nominated themselves to be sig leads.
The members will vote with a thumbs up.
The maintainers will vote with thumbs up.
If there are no objections this PR should be merged by the maintainers.
@ishitasequeira please add a comment to acknowledge your nomination.
> Establish Sig-Leads for Argo Sig Scalability

- MAINTAINERS.md
Long time no see! Thank you for having me in the Alumni list. I don’t have chances to contribute to the community now as my current company doesn’t use Kubernetes at all. By the way, my belonging company is not up-to-date in the list, so could you update it?
> Update the affiliation of dtaniwaki in the MAINTAINERS.md

- MAINTAINERS.md
- OWNERS
I can no longer in good faith continue to contribute to the project. See also https://github.com/argoproj/argo-workflows/pull/13837
- remove myself from `OWNERS`
- remove myself as active in `MAINTAINERS.md`
- aligned columns
- markdown and YAML looks correct
> chore: remove `@agilgur5` from OWNERS/Maintainers

- sigs/sig-security/README.md
In today's Maintainers' meeting, we realized the SIGs need to designate "secretaries" to be responsible for SIG communication to the broader maintainer community. Pasha volunteered and has the support of both SIG leads.
> Designate Pasha as SIG Security secretary

- sigs/sig-marketing/README.md
I'd like to nominate @revitalbarletz to sig-marketing.
Revital has a history of contributing to open-source communities most recently growing the Wing OSS community with 1k members in the last year. She's an experienced engineer and already started contributing docs to Argo CD. Over the course of KubeCon / ArgoCon she also helped craft social messages for the conference. I think she'll be a great addition in helping grow our community.
> Nominate Revital to sig-marketing
